import { getDb } from "./db";

const sampleProjects = [
  {
    project_name: "Manor Solar v2",
    description: "200 MW solar project in Albany County",
    fuel_type: "Solar",
    size_mw: 200,
    capacity_mw: 120,
    co_located: "Yes",
    state: "NY",
    county: "Albany",
    latitude: 40.7128,
    longitude: -74.006,
    iso_region: "NYISO",
    queue_number: "Q829",
    queue_cycle: "2022",
    utility: "PSEG",
    poi: "Brink - Pine Wood",
    poi_voltage: 345,
    project_manager: "John V",
    admin_emails: "edavis05@example.com;jmoore10@example.com",
    developer_emails: "bjohnson03@example.com",
    interconnection_status: "Feasibility Study",
    option_to_build: "Self-Build",
    suspension: "No",
    provisional_ia_status: "Not Available",
    security_posted_to_date: 500000,
    security_at_risk_to_date: 200000,
    study_deposits_posted: 150000,
    sunk_cost_to_date: 50000,
    interconnection_facilities_cost: 5000000,
    grid_network_upgrades: 3000000,
    affected_system_costs: 0,
    affected_system: "None",
    lgia_security: 5000000,
    next_security_milestone: 250002,
    qsa_deadline: "2024-05-23",
    next_due_date: "2024-12-02",
    planned_cod: "2026-11-30",
    security_milestones: JSON.stringify([
      { date: "2024-06-01", milestone_name: "Feasibility Study Deposit", amount: 50000, type: "deposit", at_risk: false, refundable: true },
      { date: "2024-09-01", milestone_name: "SIS Deposit", amount: 100000, type: "deposit", at_risk: false, refundable: true },
      { date: "2025-03-01", milestone_name: "Facilities Study Deposit", amount: 150000, type: "deposit", at_risk: true, refundable: false },
      { date: "2025-06-01", milestone_name: "Initial Security Posting", amount: 250000, type: "security", at_risk: true, refundable: false },
      { date: "2025-12-01", milestone_name: "IA Execution Security", amount: 500000, type: "security", at_risk: true, refundable: false },
      { date: "2026-06-01", milestone_name: "Construction Start Security", amount: 2000000, type: "security", at_risk: true, refundable: false },
      { date: "2026-11-30", milestone_name: "COD Final Security", amount: 5000000, type: "security", at_risk: true, refundable: false },
    ]),
  },
  {
    project_name: "Midwest Wind Farm",
    description: "350 MW wind project in McLean County, IL",
    fuel_type: "Wind",
    size_mw: 350,
    capacity_mw: 280,
    co_located: "No",
    state: "IL",
    county: "McLean",
    latitude: 40.4907,
    longitude: -88.9789,
    iso_region: "MISO",
    queue_number: "J1234",
    queue_cycle: "2023",
    utility: "Ameren",
    poi: "Bloomington 345kV",
    poi_voltage: 345,
    project_manager: "Sarah K",
    admin_emails: "admin@windco.com",
    developer_emails: "dev@windco.com",
    interconnection_status: "System Impact Study",
    option_to_build: "Full Build",
    suspension: "No",
    provisional_ia_status: "Not Available",
    security_posted_to_date: 2100000,
    security_at_risk_to_date: 1400000,
    study_deposits_posted: 200000,
    sunk_cost_to_date: 350000,
    interconnection_facilities_cost: 8000000,
    grid_network_upgrades: 12000000,
    affected_system_costs: 500000,
    affected_system: "PJM",
    lgia_security: 8000000,
    next_security_milestone: 1000000,
    qsa_deadline: "2025-01-15",
    next_due_date: "2025-03-01",
    planned_cod: "2027-06-30",
    miso_dpp_phase: "Phase 2",
    miso_definitive_planning_phase: "DPP",
    security_milestones: JSON.stringify([
      { date: "2024-01-15", milestone_name: "DPP Phase 1 Deposit", amount: 100000, type: "deposit", at_risk: false, refundable: true },
      { date: "2024-06-01", milestone_name: "Phase 2 M2 Milestone", amount: 500000, type: "security", at_risk: true, refundable: false },
      { date: "2025-01-01", milestone_name: "Phase 3 M3 Milestone", amount: 1000000, type: "security", at_risk: true, refundable: false },
      { date: "2025-07-01", milestone_name: "GIA Execution Security", amount: 2000000, type: "security", at_risk: true, refundable: false },
      { date: "2026-06-01", milestone_name: "Construction Security", amount: 4000000, type: "security", at_risk: true, refundable: false },
      { date: "2027-06-30", milestone_name: "COD Security", amount: 8000000, type: "security", at_risk: true, refundable: false },
    ]),
  },
  {
    project_name: "PJM Solar Hub",
    description: "150 MW solar + 50 MW storage in Lancaster County, PA",
    fuel_type: "Solar + Storage",
    size_mw: 200,
    capacity_mw: 150,
    co_located: "Yes",
    co_located_fuel_type: "Battery Storage",
    co_located_size_mw: 50,
    state: "PA",
    county: "Lancaster",
    latitude: 40.0379,
    longitude: -76.3055,
    iso_region: "PJM",
    queue_number: "AF2-345",
    queue_cycle: "Transition Cycle 1",
    utility: "PPL Electric",
    poi: "Lancaster 230kV",
    poi_voltage: 230,
    project_manager: "Mike R",
    admin_emails: "admin@pjmsolar.com",
    developer_emails: "dev@pjmsolar.com",
    interconnection_status: "Facilities Study",
    option_to_build: "Self-Build",
    suspension: "No",
    provisional_ia_status: "Eligible",
    security_posted_to_date: 3500000,
    security_at_risk_to_date: 2800000,
    study_deposits_posted: 300000,
    sunk_cost_to_date: 750000,
    interconnection_facilities_cost: 6500000,
    grid_network_upgrades: 4200000,
    affected_system_costs: 0,
    affected_system: "None",
    lgia_security: 6500000,
    next_security_milestone: 750000,
    qsa_deadline: "2024-11-01",
    next_due_date: "2025-01-15",
    planned_cod: "2027-03-31",
    pjm_queue_position: "AF2-345",
    pjm_transition_cycle: "TC1",
    pjm_cluster_window: "Window 1",
    feasibility_study_status: "Completed",
    system_impact_study_status: "Completed",
    facilities_study_status: "In Progress",
    security_milestones: JSON.stringify([
      { date: "2023-09-01", milestone_name: "Readiness Deposit", amount: 150000, type: "deposit", at_risk: false, refundable: true },
      { date: "2024-03-01", milestone_name: "Phase 1 Security (BPM-15)", amount: 500000, type: "security", at_risk: true, refundable: false },
      { date: "2024-09-01", milestone_name: "Phase 2 Security", amount: 1000000, type: "security", at_risk: true, refundable: false },
      { date: "2025-03-01", milestone_name: "Phase 3 Security", amount: 2000000, type: "security", at_risk: true, refundable: false },
      { date: "2025-09-01", milestone_name: "ISA Execution", amount: 3500000, type: "security", at_risk: true, refundable: false },
      { date: "2026-06-01", milestone_name: "Construction Milestone", amount: 5000000, type: "security", at_risk: true, refundable: false },
      { date: "2027-03-31", milestone_name: "COD Security", amount: 6500000, type: "security", at_risk: true, refundable: false },
    ]),
  },
  {
    project_name: "Desert Sun BESS",
    description: "400 MW / 1600 MWh battery storage in Riverside County",
    fuel_type: "Battery Storage",
    size_mw: 400,
    capacity_mw: 400,
    co_located: "No",
    state: "CA",
    county: "Riverside",
    latitude: 33.9533,
    longitude: -117.3961,
    iso_region: "CAISO",
    queue_number: "C567",
    queue_cycle: "Cluster 14",
    utility: "SCE",
    poi: "Devers 500kV",
    poi_voltage: 500,
    project_manager: "Lisa T",
    admin_emails: "admin@desertsun.com",
    developer_emails: "dev@desertsun.com",
    interconnection_status: "System Impact Study",
    option_to_build: "Full Build",
    suspension: "No",
    provisional_ia_status: "Not Available",
    security_posted_to_date: 4200000,
    security_at_risk_to_date: 3000000,
    study_deposits_posted: 500000,
    sunk_cost_to_date: 1200000,
    interconnection_facilities_cost: 15000000,
    grid_network_upgrades: 8000000,
    affected_system_costs: 1000000,
    affected_system: "None",
    lgia_security: 15000000,
    next_security_milestone: 2000000,
    qsa_deadline: "2025-06-30",
    next_due_date: "2025-04-15",
    planned_cod: "2028-01-15",
    caiso_cluster: "14",
    caiso_phase: "Phase 2",
    caiso_zone: "SP26",
    security_milestones: JSON.stringify([
      { date: "2024-01-01", milestone_name: "Phase 1 Study Deposit", amount: 250000, type: "deposit", at_risk: false, refundable: true },
      { date: "2024-07-01", milestone_name: "Phase 2 Study Deposit", amount: 500000, type: "deposit", at_risk: true, refundable: false },
      { date: "2025-03-01", milestone_name: "IFS Posting", amount: 2000000, type: "security", at_risk: true, refundable: false },
      { date: "2025-12-01", milestone_name: "GIA Execution Security", amount: 4000000, type: "security", at_risk: true, refundable: false },
      { date: "2026-12-01", milestone_name: "Construction Security", amount: 10000000, type: "security", at_risk: true, refundable: false },
      { date: "2028-01-15", milestone_name: "COD Security", amount: 15000000, type: "security", at_risk: true, refundable: false },
    ]),
  },
  {
    project_name: "Prairie Wind SPP",
    description: "300 MW wind farm in Woodward County, OK",
    fuel_type: "Wind",
    size_mw: 300,
    capacity_mw: 250,
    co_located: "No",
    state: "OK",
    county: "Woodward",
    latitude: 36.4238,
    longitude: -99.3904,
    iso_region: "SPP",
    queue_number: "SPP-2023-456",
    queue_cycle: "DISIS 2023-1",
    utility: "OGE",
    poi: "Woodward 345kV",
    poi_voltage: 345,
    project_manager: "Tom B",
    admin_emails: "admin@prairiewind.com",
    developer_emails: "dev@prairiewind.com",
    interconnection_status: "Feasibility Study",
    option_to_build: "Self-Build",
    suspension: "No",
    provisional_ia_status: "Not Available",
    security_posted_to_date: 900000,
    security_at_risk_to_date: 500000,
    study_deposits_posted: 100000,
    sunk_cost_to_date: 200000,
    interconnection_facilities_cost: 7000000,
    grid_network_upgrades: 5500000,
    affected_system_costs: 0,
    affected_system: "None",
    lgia_security: 7000000,
    next_security_milestone: 500000,
    qsa_deadline: "2025-08-01",
    next_due_date: "2025-05-01",
    planned_cod: "2028-06-30",
    spp_disis_cluster: "DISIS 2023-1",
    spp_study_group: "Group A",
    security_milestones: JSON.stringify([
      { date: "2024-02-01", milestone_name: "Study Deposit", amount: 100000, type: "deposit", at_risk: false, refundable: true },
      { date: "2024-08-01", milestone_name: "DISIS Security", amount: 400000, type: "security", at_risk: true, refundable: false },
      { date: "2025-04-01", milestone_name: "Facilities Study Security", amount: 900000, type: "security", at_risk: true, refundable: false },
      { date: "2026-01-01", milestone_name: "GIA Execution", amount: 2000000, type: "security", at_risk: true, refundable: false },
      { date: "2027-01-01", milestone_name: "Construction Security", amount: 4500000, type: "security", at_risk: true, refundable: false },
      { date: "2028-06-30", milestone_name: "COD Security", amount: 7000000, type: "security", at_risk: true, refundable: false },
    ]),
  },
];

export function seedDatabase() {
  const db = getDb();
  const count = db.prepare("SELECT COUNT(*) as count FROM projects").get() as { count: number };
  if (count.count > 0) return;

  const insert = db.prepare(`
    INSERT INTO projects (
      project_name, description, fuel_type, size_mw, capacity_mw, co_located,
      co_located_fuel_type, co_located_size_mw, state, county, latitude, longitude,
      iso_region, queue_number, queue_cycle, utility, poi, poi_voltage,
      project_manager, admin_emails, developer_emails,
      interconnection_status, option_to_build, suspension, provisional_ia_status, ssr_status,
      security_posted_to_date, security_at_risk_to_date, study_deposits_posted, sunk_cost_to_date,
      interconnection_facilities_cost, grid_network_upgrades, affected_system_costs, affected_system,
      lgia_security, next_security_milestone,
      qsa_deadline, next_due_date, planned_cod,
      feasibility_study_status, system_impact_study_status, facilities_study_status,
      pjm_queue_position, pjm_transition_cycle, pjm_cluster_window,
      miso_dpp_phase, miso_definitive_planning_phase,
      spp_disis_cluster, spp_study_group,
      caiso_cluster, caiso_phase, caiso_zone,
      security_milestones
    ) VALUES (
      @project_name, @description, @fuel_type, @size_mw, @capacity_mw, @co_located,
      @co_located_fuel_type, @co_located_size_mw, @state, @county, @latitude, @longitude,
      @iso_region, @queue_number, @queue_cycle, @utility, @poi, @poi_voltage,
      @project_manager, @admin_emails, @developer_emails,
      @interconnection_status, @option_to_build, @suspension, @provisional_ia_status, @ssr_status,
      @security_posted_to_date, @security_at_risk_to_date, @study_deposits_posted, @sunk_cost_to_date,
      @interconnection_facilities_cost, @grid_network_upgrades, @affected_system_costs, @affected_system,
      @lgia_security, @next_security_milestone,
      @qsa_deadline, @next_due_date, @planned_cod,
      @feasibility_study_status, @system_impact_study_status, @facilities_study_status,
      @pjm_queue_position, @pjm_transition_cycle, @pjm_cluster_window,
      @miso_dpp_phase, @miso_definitive_planning_phase,
      @spp_disis_cluster, @spp_study_group,
      @caiso_cluster, @caiso_phase, @caiso_zone,
      @security_milestones
    )
  `);

  const insertMany = db.transaction((projects: typeof sampleProjects) => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const p of projects as any[]) {
      insert.run({
        project_name: p.project_name,
        description: p.description,
        fuel_type: p.fuel_type,
        size_mw: p.size_mw,
        capacity_mw: p.capacity_mw,
        co_located: p.co_located,
        co_located_fuel_type: p.co_located_fuel_type || null,
        co_located_size_mw: p.co_located_size_mw || 0,
        state: p.state,
        county: p.county,
        latitude: p.latitude,
        longitude: p.longitude,
        iso_region: p.iso_region,
        queue_number: p.queue_number,
        queue_cycle: p.queue_cycle,
        utility: p.utility,
        poi: p.poi,
        poi_voltage: p.poi_voltage,
        project_manager: p.project_manager,
        admin_emails: p.admin_emails,
        developer_emails: p.developer_emails,
        interconnection_status: p.interconnection_status,
        option_to_build: p.option_to_build,
        suspension: p.suspension,
        provisional_ia_status: p.provisional_ia_status,
        ssr_status: p.ssr_status || null,
        security_posted_to_date: p.security_posted_to_date,
        security_at_risk_to_date: p.security_at_risk_to_date,
        study_deposits_posted: p.study_deposits_posted,
        sunk_cost_to_date: p.sunk_cost_to_date,
        interconnection_facilities_cost: p.interconnection_facilities_cost,
        grid_network_upgrades: p.grid_network_upgrades,
        affected_system_costs: p.affected_system_costs,
        affected_system: p.affected_system,
        lgia_security: p.lgia_security,
        next_security_milestone: p.next_security_milestone,
        qsa_deadline: p.qsa_deadline,
        next_due_date: p.next_due_date,
        planned_cod: p.planned_cod,
        feasibility_study_status: p.feasibility_study_status || "Not Started",
        system_impact_study_status: p.system_impact_study_status || "Not Started",
        facilities_study_status: p.facilities_study_status || "Not Started",
        pjm_queue_position: p.pjm_queue_position || null,
        pjm_transition_cycle: p.pjm_transition_cycle || null,
        pjm_cluster_window: p.pjm_cluster_window || null,
        miso_dpp_phase: p.miso_dpp_phase || null,
        miso_definitive_planning_phase: p.miso_definitive_planning_phase || null,
        spp_disis_cluster: p.spp_disis_cluster || null,
        spp_study_group: p.spp_study_group || null,
        caiso_cluster: p.caiso_cluster || null,
        caiso_phase: p.caiso_phase || null,
        caiso_zone: p.caiso_zone || null,
        security_milestones: p.security_milestones,
      });
    }
  });

  insertMany(sampleProjects);
}
