"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import ProjectForm from "@/app/components/ProjectForm";

// Fallback mock data matching detail page
const MOCK_PROJECTS: Record<number, Record<string, unknown>> = {
  1: { id: 1, project_name: "Manor Solar v2", description: "200 MW solar project in Albany County", fuel_type: "Solar", size_mw: 200, capacity_mw: 120, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "NY", county: "Albany", latitude: 42.65, longitude: -73.75, iso_region: "NYISO", queue_number: "NY-2024-0142", queue_cycle: "2024 Q1", utility: "PSEG", poi: "Brink - Pine Wood 345kV", poi_voltage: 345, project_manager: "Sarah Chen", admin_emails: "admin@dev.com", developer_emails: "dev@dev.com", interconnection_status: "Feasibility Study", option_to_build: "N/A", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 500000, security_at_risk_to_date: 200000, study_deposits_posted: 80000, sunk_cost_to_date: 120000, interconnection_facilities_cost: 15000000, grid_network_upgrades: 8500000, affected_system_costs: 2000000, affected_system: "Con Edison", lgia_security: 0, next_security_milestone: 300000, qsa_deadline: "2025-09-01", next_due_date: "2025-06-15", planned_cod: "2026-11-01", feasibility_study_status: "In Progress", feasibility_study_completion_date: "2025-08-01", system_impact_study_status: "Not Started", system_impact_study_completion_date: "", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2025-01-15", updated_at: "2025-03-01" },
  2: { id: 2, project_name: "Midwest Wind Farm", description: "350 MW wind farm in McLean County, IL", fuel_type: "Wind", size_mw: 350, capacity_mw: 280, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "IL", county: "McLean", latitude: 40.49, longitude: -88.99, iso_region: "MISO", queue_number: "J1042", queue_cycle: "DPP 2023", utility: "Ameren", poi: "Bloomington 345kV", poi_voltage: 345, project_manager: "Mike Torres", admin_emails: "", developer_emails: "", interconnection_status: "System Impact Study", option_to_build: "N/A", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 2100000, security_at_risk_to_date: 1400000, study_deposits_posted: 250000, sunk_cost_to_date: 380000, interconnection_facilities_cost: 22000000, grid_network_upgrades: 18000000, affected_system_costs: 4500000, affected_system: "PJM", lgia_security: 0, next_security_milestone: 1800000, qsa_deadline: "", next_due_date: "2025-09-01", planned_cod: "2027-06-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2024-12-01", system_impact_study_status: "In Progress", system_impact_study_completion_date: "2025-06-01", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "Phase 2", miso_definitive_planning_phase: "DPP 2023", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2024-11-01", updated_at: "2025-02-15" },
  3: { id: 3, project_name: "PJM Solar Hub", description: "200 MW solar + storage hybrid in Lancaster County", fuel_type: "Solar + Storage", size_mw: 200, capacity_mw: 150, co_located: "Yes", co_located_fuel_type: "Battery Storage", co_located_size_mw: 50, state: "PA", county: "Lancaster", latitude: 40.04, longitude: -76.31, iso_region: "PJM", queue_number: "AH1-234", queue_cycle: "Transition Cycle 1", utility: "PPL Electric", poi: "Susquehanna 500kV", poi_voltage: 500, project_manager: "Emily Johnson", admin_emails: "", developer_emails: "", interconnection_status: "Facilities Study", option_to_build: "Self-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 3500000, security_at_risk_to_date: 2800000, study_deposits_posted: 400000, sunk_cost_to_date: 550000, interconnection_facilities_cost: 30000000, grid_network_upgrades: 25000000, affected_system_costs: 3200000, affected_system: "NYISO", lgia_security: 0, next_security_milestone: 2400000, qsa_deadline: "", next_due_date: "2025-08-01", planned_cod: "2027-03-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2024-06-01", system_impact_study_status: "Completed", system_impact_study_completion_date: "2024-11-15", facilities_study_status: "In Progress", facilities_study_completion_date: "2025-05-01", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "AH1-234", pjm_transition_cycle: "Transition Cycle 1", pjm_cluster_window: "2023 Q4", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2024-08-01", updated_at: "2025-01-20" },
  4: { id: 4, project_name: "Desert Sun BESS", description: "400 MW battery storage in Riverside County, CA", fuel_type: "Battery Storage", size_mw: 400, capacity_mw: 400, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "CA", county: "Riverside", latitude: 33.95, longitude: -117.39, iso_region: "CAISO", queue_number: "CL2023-456", queue_cycle: "Cluster 15", utility: "SCE", poi: "Devers 230kV", poi_voltage: 230, project_manager: "James Wright", admin_emails: "", developer_emails: "", interconnection_status: "System Impact Study", option_to_build: "TO-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 4200000, security_at_risk_to_date: 3000000, study_deposits_posted: 500000, sunk_cost_to_date: 720000, interconnection_facilities_cost: 35000000, grid_network_upgrades: 28000000, affected_system_costs: 0, affected_system: "", lgia_security: 0, next_security_milestone: 3300000, qsa_deadline: "", next_due_date: "2025-12-01", planned_cod: "2028-01-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2024-09-01", system_impact_study_status: "In Progress", system_impact_study_completion_date: "2025-09-01", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "Cluster 15", caiso_phase: "Phase II", caiso_zone: "SP26", serc_queue_id: "", security_milestones: "[]", created_at: "2024-06-15", updated_at: "2025-02-01" },
  5: { id: 5, project_name: "Prairie Wind SPP", description: "300 MW wind project in Woodward County, OK", fuel_type: "Wind", size_mw: 300, capacity_mw: 250, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "OK", county: "Woodward", latitude: 36.42, longitude: -99.39, iso_region: "SPP", queue_number: "DISIS-2024-089", queue_cycle: "DISIS 2024", utility: "OGE", poi: "Woodward 345kV", poi_voltage: 345, project_manager: "Lisa Park", admin_emails: "", developer_emails: "", interconnection_status: "Feasibility Study", option_to_build: "N/A", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 900000, security_at_risk_to_date: 500000, study_deposits_posted: 120000, sunk_cost_to_date: 180000, interconnection_facilities_cost: 12000000, grid_network_upgrades: 9000000, affected_system_costs: 1500000, affected_system: "MISO", lgia_security: 0, next_security_milestone: 1200000, qsa_deadline: "", next_due_date: "2025-07-15", planned_cod: "2028-06-01", feasibility_study_status: "In Progress", feasibility_study_completion_date: "2025-06-01", system_impact_study_status: "Not Started", system_impact_study_completion_date: "", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "DISIS 2024-1", spp_study_group: "SG-24-089", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2025-01-10", updated_at: "2025-03-05" },
  6: { id: 6, project_name: "Texas Solar Ranch", description: "500 MW utility-scale solar in Webb County, TX", fuel_type: "Solar", size_mw: 500, capacity_mw: 450, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "TX", county: "Webb", latitude: 27.56, longitude: -99.49, iso_region: "ERCOT", queue_number: "INR-2023-1105", queue_cycle: "2023", utility: "Oncor", poi: "Laredo 345kV", poi_voltage: 345, project_manager: "Carlos Mendez", admin_emails: "", developer_emails: "", interconnection_status: "Commercial Operation", option_to_build: "TO-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 6000000, security_at_risk_to_date: 0, study_deposits_posted: 350000, sunk_cost_to_date: 900000, interconnection_facilities_cost: 45000000, grid_network_upgrades: 38000000, affected_system_costs: 0, affected_system: "", lgia_security: 0, next_security_milestone: 0, qsa_deadline: "", next_due_date: "", planned_cod: "2025-09-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2023-06-01", system_impact_study_status: "Completed", system_impact_study_completion_date: "2024-01-15", facilities_study_status: "Completed", facilities_study_completion_date: "2024-06-01", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "2024-09-15", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2023-05-01", updated_at: "2025-09-01" },
  7: { id: 7, project_name: "Appalachian Wind", description: "275 MW wind project in Grant County, WV", fuel_type: "Wind", size_mw: 275, capacity_mw: 220, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "WV", county: "Grant", latitude: 38.99, longitude: -79.18, iso_region: "PJM", queue_number: "AF2-567", queue_cycle: "Transition Cycle 2", utility: "AEP", poi: "Mt Storm 500kV", poi_voltage: 500, project_manager: "David Kim", admin_emails: "", developer_emails: "", interconnection_status: "Feasibility Study", option_to_build: "Self-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 400000, security_at_risk_to_date: 150000, study_deposits_posted: 60000, sunk_cost_to_date: 95000, interconnection_facilities_cost: 18000000, grid_network_upgrades: 14000000, affected_system_costs: 2500000, affected_system: "MISO", lgia_security: 0, next_security_milestone: 500000, qsa_deadline: "", next_due_date: "2025-10-01", planned_cod: "2029-03-01", feasibility_study_status: "In Progress", feasibility_study_completion_date: "2025-08-01", system_impact_study_status: "Not Started", system_impact_study_completion_date: "", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "AF2-567", pjm_transition_cycle: "Transition Cycle 2", pjm_cluster_window: "2024 Q1", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2025-02-01", updated_at: "2025-03-10" },
  8: { id: 8, project_name: "Nevada BESS", description: "250 MW battery storage in Clark County, NV", fuel_type: "Battery Storage", size_mw: 250, capacity_mw: 250, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "NV", county: "Clark", latitude: 36.17, longitude: -115.14, iso_region: "CAISO", queue_number: "CL2023-789", queue_cycle: "Cluster 15", utility: "NVE", poi: "Eldorado 230kV", poi_voltage: 230, project_manager: "Anna Rivera", admin_emails: "", developer_emails: "", interconnection_status: "Facilities Study", option_to_build: "TO-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 2800000, security_at_risk_to_date: 2200000, study_deposits_posted: 300000, sunk_cost_to_date: 420000, interconnection_facilities_cost: 20000000, grid_network_upgrades: 16000000, affected_system_costs: 0, affected_system: "", lgia_security: 0, next_security_milestone: 2000000, qsa_deadline: "", next_due_date: "2025-11-01", planned_cod: "2027-09-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2024-07-01", system_impact_study_status: "Completed", system_impact_study_completion_date: "2024-12-01", facilities_study_status: "In Progress", facilities_study_completion_date: "2025-07-01", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "Cluster 15", caiso_phase: "Phase II", caiso_zone: "SP26", serc_queue_id: "", security_milestones: "[]", created_at: "2024-07-15", updated_at: "2025-01-30" },
  9: { id: 9, project_name: "Gulf Coast Wind", description: "450 MW wind farm in Cameron County, LA", fuel_type: "Wind", size_mw: 450, capacity_mw: 380, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "LA", county: "Cameron", latitude: 29.80, longitude: -93.33, iso_region: "MISO", queue_number: "J1198", queue_cycle: "DPP 2024", utility: "Entergy", poi: "Nelson 230kV", poi_voltage: 230, project_manager: "Robert Williams", admin_emails: "", developer_emails: "", interconnection_status: "System Impact Study", option_to_build: "N/A", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 1500000, security_at_risk_to_date: 1000000, study_deposits_posted: 200000, sunk_cost_to_date: 310000, interconnection_facilities_cost: 28000000, grid_network_upgrades: 22000000, affected_system_costs: 5000000, affected_system: "SPP", lgia_security: 0, next_security_milestone: 2800000, qsa_deadline: "", next_due_date: "2025-08-15", planned_cod: "2028-09-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2025-01-15", system_impact_study_status: "In Progress", system_impact_study_completion_date: "2025-07-01", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "Phase 1", miso_definitive_planning_phase: "DPP 2024", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2024-09-01", updated_at: "2025-02-20" },
  10: { id: 10, project_name: "Carolina Hybrid", description: "320 MW solar + storage hybrid in Cumberland County, NC", fuel_type: "Solar + Storage", size_mw: 320, capacity_mw: 260, co_located: "Yes", co_located_fuel_type: "Battery Storage", co_located_size_mw: 80, state: "NC", county: "Cumberland", latitude: 35.05, longitude: -78.88, iso_region: "PJM", queue_number: "AH2-890", queue_cycle: "Transition Cycle 2", utility: "Duke", poi: "Fayetteville 230kV", poi_voltage: 230, project_manager: "Patricia Lee", admin_emails: "", developer_emails: "", interconnection_status: "System Impact Study", option_to_build: "Self-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 1800000, security_at_risk_to_date: 1200000, study_deposits_posted: 280000, sunk_cost_to_date: 350000, interconnection_facilities_cost: 24000000, grid_network_upgrades: 19000000, affected_system_costs: 3000000, affected_system: "", lgia_security: 0, next_security_milestone: 1600000, qsa_deadline: "", next_due_date: "2025-09-15", planned_cod: "2028-03-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2024-10-01", system_impact_study_status: "In Progress", system_impact_study_completion_date: "2025-06-15", facilities_study_status: "Not Started", facilities_study_completion_date: "", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "AH2-890", pjm_transition_cycle: "Transition Cycle 2", pjm_cluster_window: "2024 Q2", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2024-10-01", updated_at: "2025-02-28" },
  11: { id: 11, project_name: "Kansas Wind Farm", description: "400 MW wind farm in Ford County, KS", fuel_type: "Wind", size_mw: 400, capacity_mw: 340, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "KS", county: "Ford", latitude: 37.77, longitude: -99.89, iso_region: "SPP", queue_number: "DISIS-2022-045", queue_cycle: "DISIS 2022", utility: "Evergy", poi: "Dodge City 345kV", poi_voltage: 345, project_manager: "Tom Anderson", admin_emails: "", developer_emails: "", interconnection_status: "Commercial Operation", option_to_build: "TO-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 7500000, security_at_risk_to_date: 0, study_deposits_posted: 400000, sunk_cost_to_date: 1200000, interconnection_facilities_cost: 55000000, grid_network_upgrades: 42000000, affected_system_costs: 8000000, affected_system: "MISO", lgia_security: 0, next_security_milestone: 0, qsa_deadline: "", next_due_date: "", planned_cod: "2025-12-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2023-03-01", system_impact_study_status: "Completed", system_impact_study_completion_date: "2023-09-01", facilities_study_status: "Completed", facilities_study_completion_date: "2024-03-01", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "2024-07-15", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "DISIS 2022-1", spp_study_group: "SG-22-045", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2022-06-01", updated_at: "2025-12-01" },
  12: { id: 12, project_name: "New England Solar", description: "120 MW solar project in Berkshire County, MA", fuel_type: "Solar", size_mw: 120, capacity_mw: 100, co_located: "No", co_located_fuel_type: "", co_located_size_mw: 0, state: "MA", county: "Berkshire", latitude: 42.45, longitude: -73.25, iso_region: "ISO-NE", queue_number: "NE-2024-0331", queue_cycle: "2024", utility: "Eversource", poi: "Berkshire 115kV", poi_voltage: 115, project_manager: "Jennifer White", admin_emails: "", developer_emails: "", interconnection_status: "Facilities Study", option_to_build: "Self-Build", suspension: "No", provisional_ia_status: "", ssr_status: "", security_posted_to_date: 1200000, security_at_risk_to_date: 900000, study_deposits_posted: 150000, sunk_cost_to_date: 210000, interconnection_facilities_cost: 10000000, grid_network_upgrades: 7500000, affected_system_costs: 1000000, affected_system: "NYISO", lgia_security: 0, next_security_milestone: 800000, qsa_deadline: "", next_due_date: "2025-07-01", planned_cod: "2027-06-01", feasibility_study_status: "Completed", feasibility_study_completion_date: "2024-11-01", system_impact_study_status: "Completed", system_impact_study_completion_date: "2025-02-15", facilities_study_status: "In Progress", facilities_study_completion_date: "2025-06-01", phase3_study_status: "Not Started", phase3_study_completion_date: "", ia_execution_date: "", congestion_results: "", power_flow_results: "", pjm_queue_position: "", pjm_transition_cycle: "", pjm_cluster_window: "", miso_dpp_phase: "", miso_definitive_planning_phase: "", spp_disis_cluster: "", spp_study_group: "", caiso_cluster: "", caiso_phase: "", caiso_zone: "", serc_queue_id: "", security_milestones: "[]", created_at: "2024-12-01", updated_at: "2025-03-01" },
};

export default function EditProjectPage() {
  const params = useParams();
  const [project, setProject] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const pid = Number(params.id);
    fetch(`/api/projects/${pid}`)
      .then((r) => {
        if (!r.ok) throw new Error("API unavailable");
        return r.json();
      })
      .then((data) => {
        if (data && data.id) {
          setProject(data);
        } else {
          setProject(MOCK_PROJECTS[pid] || null);
        }
        setLoading(false);
      })
      .catch(() => {
        setProject(MOCK_PROJECTS[pid] || null);
        setLoading(false);
      });
  }, [params.id]);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-slate-200 border-t-amber-500" />
      </div>
    );
  }

  if (!project) {
    return (
      <div className="mx-auto max-w-5xl px-4 py-16 text-center">
        <p className="text-lg text-slate-500">Project not found</p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
      <Link href={`/projects/${params.id}`} className="text-sm text-slate-500 hover:text-slate-700">
        ← Back to Project
      </Link>
      <h1 className="mt-4 mb-6 text-2xl font-bold text-slate-900">Edit Project</h1>
      <ProjectForm initialData={project} isEdit />
    </div>
  );
}
